name: Waka Readme

on:
  schedule:
    # 每天凌晨 0 点自动运行 (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # 允许你手动点击按钮运行

jobs:
  update-readme:
    name: Update Dev Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: "false" # 关掉代码行数（因为免费版拿不到这个数据）
          SHOW_PROJECTS: "true"
          SHOW_EDITORS: "true"
          SHOW_OS: "true"
          REPOSITORY: bessonzhao/my-wakatime-stats
